Djupvikv01/Models/ArticleModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Djupvikv01.Models
{
    public class ArticleModel
    {
        public int id { get; set; }
        [Required]
        public string forfattare { get; set; }
        [Required]
        public string artikeltyp { get; set; }
        [Required]
        public string rubrik { get; set; }
        [Required]
        public string sammanfattning { get; set; }
        [Required]
        public string innehall { get; set; }
        [Required]
        public string bild { get; set; }
        [Required]
        public string datum { get; set; }
     


        public ArticleModel()
        {
      
        }
   
        public ArticleModel(int id, string forfattare, string artikeltyp, string rubrik, string sammanfattning, string innehall, string bild, string datum)
        {
            this.id = id;
            this.forfattare = forfattare;
            this.artikeltyp = artikeltyp;
            this.rubrik = rubrik;
            this.sammanfattning = sammanfattning;
            this.innehall = innehall;
            this.bild = bild;
            this.datum = datum;
        }
 
    }
}



 

Djupvikv01/Models/ArticletypModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Djupvikv01.Models
{


    public class ArticletypModel
    {
        public int id { get; set; }
        public string artikeltyp { get; set; }
       

         


 
    public ArticletypModel()
    {
         
    }

    public ArticletypModel(int id, string artyplist)
    {
        this.id = id;
        this.artikeltyp = artikeltyp;
 
 
    }



 




}
}





Djupvikv01/Models/ErrorViewModel.cs
using System;

namespace Djupvikv01.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Djupvikv01/Models/UsersModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Djupvikv01.Models
{


    public class UsersModel
    {
        public int id { get; set; }
        public string anvandarnamn { get; set; }
        public string namn { get; set; }
        public string losenord { get; set; }
        public string email { get; set; }
        public string datum { get; set; }

         


 
    public UsersModel()
    {
         
    }

    public UsersModel(int id, string anvandarnamn, string namn, string losenord, string email, string datum)
    {
        this.id = id;
        this.anvandarnamn = anvandarnamn;
        this.namn = namn;
        this.losenord = losenord;
        this.email = email;
        this.datum = datum;
 
    }



 




}
}





Djupvikv01/Controllers/PanelController.cs
using Djupvikv01.Controllers;
using Djupvikv01.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;
using System.Dynamic;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.Web;
 

namespace Djupvikv01.Controllers
{
    public class PanelController : Controller
    {
       
 


        /*
        public IActionResult Index()
        {
            List<PanelModel> articles = new List<PanelModel>();
            PanelDataObject artikelobj = new PanelDataObject();
            articles = artikelobj.hamta();
            return View("Index", articles);
        }
        */
        public IActionResult Index()
        { 
            ArticleData artikelobj = new ArticleData();
            UsersData userslist = new UsersData();
            ArticletypData artyplist = new ArticletypData();
            dynamic dy = new ExpandoObject();
            dy.artikelobj = artikelobj.hamta();
            dy.userslist = userslist.hamtaUsers();
            dy.artyplist = artyplist.hamtaArtikeltyp();
            //    dy.listType = getArtType();
            // dy.listUser = getUser();


            return View(dy);

        }


      

        public ActionResult Details(int id)
        {
            ArticleData articles = new ArticleData();
            ArticleModel article = articles.hamtaDetail(id);
            return View("Details", article);
        }



   


        public ActionResult Create(int id)
        {
            ArticleData articles = new ArticleData();
            ArticleModel article = articles.hamtaDetail(id);
            return View("AddForm", article);

        }

        public ActionResult Picker()
        {
 
            return View("Picker");

        }


 
     
        public ActionResult Edit(int id)
        {
            ArticleData articles = new ArticleData();
            ArticleModel article = articles.hamtaDetail(id);
            return View("AddForm", article);

        }


        public ActionResult ProcessCreate(ArticleModel panelModel)
        {
            ArticleData dataObject = new ArticleData();
            dataObject.CreateOrUpdate(panelModel);
            return View("Details", panelModel);
        }






        public ActionResult Delete(int id)
        {
            ArticleData articles = new ArticleData();
            articles.Delete(id);
            //List<ArticleModel> article = articles.hamta();
            return View("Action");

        }
         

        public ActionResult Action()
        {
            return View("Action");

        }

      

        public ActionResult Search(string keyword)
        {

            ArticleData artikelobj = new ArticleData();
            UsersData userslist = new UsersData();

            dynamic sr = new ExpandoObject();
            sr.artikelobj = artikelobj.Find(keyword);
 
            return View(sr);

        }




        public ActionResult Fil(string author)
        {

            ArticleData artikelobj = new ArticleData();
            UsersData userslist = new UsersData();

            dynamic filt = new ExpandoObject();
            filt.artikelobj = artikelobj.Fil(author);

            return View(filt);

        }




        public ActionResult Sorting(string sort)
        {

            ArticleData artikelobj = new ArticleData();
            UsersData userslist = new UsersData();

            dynamic filt = new ExpandoObject();
            filt.artikelobj = artikelobj.Sorting(sort);

            return View(filt);

        }







    }
}
 

Djupvikv01/Views/Panel/Action.cshtml
@model Djupvikv01.Models.ArticleModel
@{
    ViewData["Title"] = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="jumbotron mt-1">

    @using (Html.BeginForm("Find", "Panel"))
    {

        <h1> Success</h1>

        <h4>
       
  Vad vill du göra nu?
            <br />

            <a href="/Panel/">Tillbaka</a>

        </h4>



    }

</div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Djupvikv01/Views/Panel/AddForm.cshtml
@model Djupvikv01.Models.ArticleModel
<script src="~/ckeditor5/ckeditor.js"></script>

@{
    ViewData["Title"] = "Create";

}
<script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>

<div class="jumbotron mt-1">


    @using (Html.BeginForm("ProcessCreate", "Panel"))
    {
        @Html.AntiForgeryToken();


        string Date = DateTime.Now.ToString("yyyy-MM-dd HH:MM:ss");
        <h1>Skriv en ny artikel</h1>


        <hr />




        <form asp-action="Create">

            <label for="artikeltyp" class="control-label"> Välj Artikeltyp - Nuvarande @Model.artikeltyp </label>
            <select name="artikeltyp" asp-for="artikeltyp" class="form-control">

                <option value="1">Nyheter</option>
                <option value="2">Kultur</option>
                <option value="3">Vetenskap</option>
                <option value="4">Hälsa</option>
                <option value="5">Film</option>

            </select>



            <div class="form-group d-none">
                <label>Författare:</label>
                <input value="1" asp-for="forfattare" class="form-control" required />
                <span asp-validation-for="forfattare" class="text-danger"></span>
            </div>



            <label>Rubrik:</label>
            <div class="form-group">
                <input asp-for="rubrik" class="form-control" required />
                <span asp-validation-for="rubrik" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="sammanfattning" class="control-label"></label>
                <input asp-for="sammanfattning" class="form-control" required />

                <span asp-validation-for="sammanfattning" class="text-danger"></span>
            </div>



            <div class="form-group">
                <label class="control-label">Innehåll</label>

                <textarea id="editor" asp-for="innehall" mode="multiline" runat="server" class="form-control" rows="10" cols="20">
                </textarea>

                <span asp-validation-for="innehall" class="text-danger"></span>
            </div>






            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"> <a onclick="myFunction()"> Välj bild  <i class="fas fa-images"></i> </a></span>
                </div>
                <input id="enBildId" asp-for="bild" class="form-control" required />
                <span asp-validation-for="bild" class="text-danger"></span>
            </div>




            <div class="form-group d-none">
                <label asp-for="datum" class="control-label"></label>
                <input asp-for="datum" class="form-control" value="@Date" required />
                <span asp-validation-for="datum" class="text-danger"></span>
            </div>


            <input type="hidden" name="id" id="id" value="@Model.id" />


            <div class="form-group">
                <input type="submit" value="Spara" class="btn btn-primary" />
            </div>
        </form>




    }
</div>


<script>
    function myFunction() {
        window.open("/Panel/Picker", "_blank", "location=no, directories=no, status=no, menubar=no,toolbar=no,scrollbars=yes,resizable=no,top=100,left=500,width=600,height=680");
    }




    ClassicEditor
        .create(document.querySelector('#editor'),
            {
                //extraPlugins: [MyCustomUploadAdapterPlugin],
            })

        .then(editor => {
            window.editor = editor;
        })
        .catch(error => {
            console.error(error);
        });
</script>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}








Djupvikv01/Views/Panel/AddForm1.cshtml
@model Djupvikv01.Models.ArticleModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("ProcessCreate", "Panel"))
{
    @Html.AntiForgeryToken();


    <h1>Create</h1>


    <h4>PanelModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="forfattare" class="control-label"></label>
                    <input asp-for="forfattare" class="form-control" required />
                    <span asp-validation-for="forfattare" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="artikeltyp" class="control-label"></label>
                    <input asp-for="artikeltyp" class="form-control" required />
                    <span asp-validation-for="artikeltyp" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="rubrik" class="control-label"></label>
                    <input asp-for="rubrik" class="form-control" required />
                    <span asp-validation-for="rubrik" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="sammanfattning" class="control-label"></label>
                    <input asp-for="sammanfattning" class="form-control" required />
                    <span asp-validation-for="sammanfattning" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="innehall" class="control-label"></label>
                    <input asp-for="innehall" class="form-control" required />
                    <span asp-validation-for="innehall" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="bild" class="control-label"></label>
                    <input asp-for="bild" class="form-control" required />
                    <span asp-validation-for="bild" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="datum" class="control-label"></label>
                    <input asp-for="datum" class="form-control" required />
                    <span asp-validation-for="datum" class="text-danger"></span>
                </div>

                <input type="text" name="id" id="id" value="@Model.id" />


                <div class="form-group">
                    <input type="submit" value="Spara" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Djupvikv01/Views/Panel/Details.cshtml
@model Djupvikv01.Models.ArticleModel
 

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="jumbotron mt-1">
    <div>
        <h4>  @Html.DisplayFor(model => model.rubrik)</h4>
        <hr />

        <p class="bg-light p-2">

            <img class="rounded" src="@Html.DisplayFor(model => model.bild)d" alt="Jordgubbe" width="100" />
        </p>
        <p class="bg-light p-2">
            @Html.DisplayFor(model => model.sammanfattning)
        </p>
        <p class="bg-light p-2">


          
            @Html.Raw(Model.innehall)

        </p>

        <p class="bg-light p-2">
            @Html.DisplayFor(model => model.datum)

        </p>
        <p class="bg-warning p-2">
            <a href="/Panel/"> <i class="fas fa-arrow-left"></i> Tillbaka </a>
        </p>
    </div>
</div>

Djupvikv01/Views/Panel/Fil.cshtml
@using Djupvikv01.Models;
@model dynamic;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="jumbotron mt-1">
    <h1 class="ml-4">Artikel filtrering</h1>
    Nedan kan du välja namn på författare för att visa författarens artiklar
    <hr />

    <div class="jumbotron mt-1">
        <form action="/Panel/Fil" method="get" class="form-inline my-2 my-lg-0">
       
            <select name="author" class="form-control mr-sm-2">
                <option value="0" selected>Välja författare</option>
                <option value="1">Adam</option>
                <option value="2">Bob</option>
                <option value="3">Charlie</option>
                <option value="4">David</option>
            </select>

            <button class="btn btn-success my-2 my-sm-0" type="submit">Filtrera</button>
        </form>



   



        <hr />


        @foreach (ArticleModel ar in Model.artikelobj)
        {
            <div class="bg-light p-4 mt-1 rounded">

                <h4> @ar.rubrik </h4>
                <hr />
                @ar.sammanfattning
                <br />

                <a href="/Panel/Details/@ar.id">Visa mer</a>


            </div>
        }
    </div>

Djupvikv01/Views/Panel/Index.cshtml

@using Djupvikv01.Models;
@model dynamic;



@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<div class="jumbotron mt-1">
    <h4 class="ml-4">ARTIKLAR</h4>

    @foreach (ArticleModel ar in Model.artikelobj)
    {

 

            <div class="container">

                <div class="row bg-light mt-1 p-2 rounded">
                    <div class="col-sm">
                  
                        <h5> @ar.rubrik</h5> 
                        <span>@ar.datum</span>
                        <p>
                            <img class="rounded" src="@ar.bild" alt="Jordgubbe" width="50" />
                        </p>
                    </div>


                    <div class="col-auto">
                        <a href="/Panel/Details/@ar.id">Visa <i class="fas fa-eye"></i></a>
                        |
                        <a href="/Panel/Edit/@ar.id">Ändra <i class="far fa-edit"></i> </a>
                        |
                        <a href="/Panel/Delete/@ar.id">Radera <i class="fas fa-trash"></i> </a>
                    </div>
                </div>
            </div>
        

            }

    </div>
 


<div class="jumbotron mt-1">
    <h4 class="ml-4">MEDLEMMAR</h4> 

    @foreach (UsersModel user in Model.userslist)
    {
    <p class="bg-light p-2 m-1 rounded">


        <i class="fas fa-user"></i> Namn:   @user.namn <br />
         <i class="fas fa-envelope"></i>  Email:  @user.email <br />
       <i class="fas fa-calendar-alt"></i>  Registrerats:  @user.datum

    </p>
    }
    </div>


<div class="jumbotron mt-1">


    <h1 class="ml-4">Artikel filtrering</h1>
    Nedan kan du välja namn på författare för att visa författarens artiklar

    <form action="/Panel/Fil" method="get" class="form-inline my-2 my-lg-0">

        <select name="author" class="form-control mr-sm-2">
            <option value="0" selected>Välja författare</option>
            <option value="1">Adam</option>
            <option value="2">Bob</option>
            <option value="3">Charlie</option>
            <option value="4">David</option>
        </select>

        <button class="btn btn-success my-2 my-sm-0" type="submit">Filtrera</button>
    </form>





    <div class="d-none">
        Artikeltyp
        @foreach (ArticletypModel artyp in Model.artyplist)
        {

            if (@artyp.id == 1)
            {
                <p>

                    @artyp.id
                    @artyp.artikeltyp


                </p>
            }
        }
    </div>



    <hr />



    <h1 class="ml-4">Artikel sortering</h1>
    Välj nedan hur du vill sortera artiklarna...

    <div class="jumbotron mt-1">
        <form action="/Panel/Sorting" method="get" class="form-inline my-2 my-lg-0">

            <select name="sort" class="form-control mr-sm-2">
                <option value="0" selected>Sortera artiklar</option>
                <option value="id">ID</option>
                <option value="title">ALFABET</option>
            </select>

            <button class="btn btn-success my-2 my-sm-0" type="submit">Sortera</button>
        </form>












    </div>

Djupvikv01/Views/Panel/Picker.cshtml

 
<div class="container">


    <img class="img-thumbnail shadow-sm" width="100" height="100" title="Klicka här för att välja bilden"
         src="https://cdn.pixabay.com/photo/2021/08/29/13/19/kingfisher-6583229_960_720.jpg" onclick="setvalue('https://cdn.pixabay.com/photo/2021/08/29/13/19/kingfisher-6583229_960_720.jpg')" />

    <img class="img-thumbnail shadow-sm" width="100" height="100" title="Klicka här för att välja bilden"
         src="https://cdn.pixabay.com/photo/2021/09/19/12/19/animal-6637774_960_720.jpg" onclick="setvalue('https://cdn.pixabay.com/photo/2021/09/19/12/19/animal-6637774_960_720.jpg')" />

    <img class="img-thumbnail shadow-sm" width="100" height="100" title="Klicka här för att välja bilden"
         src="https://cdn.pixabay.com/photo/2021/03/29/01/54/wallaby-6132753_960_720.jpg" onclick="setvalue('https://cdn.pixabay.com/photo/2021/03/29/01/54/wallaby-6132753_960_720.jpg')" />

    <img class="img-thumbnail shadow-sm" width="100" height="100" title="Klicka här för att välja bilden"
         src="https://cdn.pixabay.com/photo/2021/09/20/21/32/lake-6641880_960_720.jpg" onclick="setvalue('https://cdn.pixabay.com/photo/2021/09/20/21/32/lake-6641880_960_720.jpg')" />


    <img class="img-thumbnail shadow-sm" width="100" height="100" title="Klicka här för att välja bilden"
         src="https://cdn.pixabay.com/photo/2021/07/15/11/15/woman-6468147__340.jpg" onclick="setvalue('https://cdn.pixabay.com/photo/2021/07/15/11/15/woman-6468147__340.jpg')" />



    <img class="img-thumbnail shadow-sm" width="100" height="100" title="Klicka här för att välja bilden"
         src="https://cdn.pixabay.com/photo/2020/11/25/03/04/russian-blue-cat-5774414__340.jpg" onclick="setvalue('https://cdn.pixabay.com/photo/2020/11/25/03/04/russian-blue-cat-5774414__340.jpg')" />



    <img class="img-thumbnail shadow-sm" width="100" height="100" title="Klicka här för att välja bilden"
         src="https://cdn.pixabay.com/photo/2021/09/06/01/13/coffee-6600644__340.jpg" onclick="setvalue('https://cdn.pixabay.com/photo/2021/09/06/01/13/coffee-6600644__340.jpg')" />


    <img class="img-thumbnail shadow-sm" width="100" height="100" title="Klicka här för att välja bilden"
         src="https://cdn.pixabay.com/photo/2021/05/14/01/56/child-6252212__340.jpg" onclick="setvalue('https://cdn.pixabay.com/photo/2021/05/14/01/56/child-6252212__340.jpg')" />


    <img class="img-thumbnail shadow-sm" width="100" height="100" title="Klicka här för att välja bilden"
         src="https://cdn.pixabay.com/photo/2021/09/15/12/34/woman-6626742__340.jpg" onclick="setvalue('https://cdn.pixabay.com/photo/2021/09/15/12/34/woman-6626742__340.jpg')" />

    <img class="img-thumbnail shadow-sm" width="100" height="100" title="Klicka här för att välja bilden"
         src="https://cdn.pixabay.com/photo/2021/08/25/21/44/woman-6574533__340.jpg" onclick="setvalue('https://cdn.pixabay.com/photo/2021/08/25/21/44/woman-6574533__340.jpg')" />



    <img class="img-thumbnail shadow-sm" width="100" height="100" title="Klicka här för att välja bilden"
         src="https://cdn.pixabay.com/photo/2021/07/19/15/47/lily-6478427__340.jpg" onclick="setvalue('https://cdn.pixabay.com/photo/2021/07/19/15/47/lily-6478427__340.jpg')" />

    <img class="img-thumbnail shadow-sm" width="100" height="100" title="klicka"
         src="https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Shiba_Inu_coin_logo.png/150px-Shiba_Inu_coin_logo.png" onclick="setvalue('https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Shiba_Inu_coin_logo.png/150px-Shiba_Inu_coin_logo.png')" />



</div>

 
<script>


    function setvalue(bildid) {
        console.log(window.opener);
        window.opener.document.getElementById('enBildId').value = bildid;
        window.close();
    }

</script>


Djupvikv01/Views/Panel/Search.cshtml

@using Djupvikv01.Models;
@model dynamic;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron mt-1">
 <h1 class="ml-4">Resultat</h1>
    <hr />


    @foreach (ArticleModel ar in Model.artikelobj)
    {
<div class="bg-light p-4 mt-1 rounded">

    <h4> @ar.rubrik </h4>
    <hr />
    @ar.sammanfattning
    <br />

    <a href="/Panel/Details/@ar.id">Visa mer</a>


</div>
    }
    </div> 
 

Djupvikv01/Views/Panel/Sorting.cshtml
@using Djupvikv01.Models;
@model dynamic;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="jumbotron mt-1">


    <h1 class="ml-4">Artikel sortering</h1>
    Välj nedan hur du vill sortera artiklarna...
    <hr />

    <div class="jumbotron mt-1">
        <form action="/Panel/Sorting" method="get" class="form-inline my-2 my-lg-0">

            <select name="sort" class="form-control mr-sm-2">
                <option value="0" selected>Sortera artiklar</option>
                <option value="id">ID</option>
                <option value="title">ALFABET</option>
            </select>

            <button class="btn btn-success my-2 my-sm-0" type="submit">Sortera</button>
        </form>

         


        <hr />


        @foreach (ArticleModel ar in Model.artikelobj)
        {
    <div class="bg-light p-4 mt-1 rounded">

        <h4>   <i class="far fa-bookmark"></i>  @ar.rubrik </h4>
        <hr />
        @ar.sammanfattning
        <br />
        Artikelnr [@ar.id]
        <a href="/Panel/Details/@ar.id">Visa mer</a>


    </div>
        }
    </div>

Djupvikv01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Djupvikv01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
<header class="bg-dark">


<nav class="navbar navbar-expand-lg navbar-dark  container">
<a class="navbar-brand" href="/Panel/"> PANEL <i class="fas fa-database"></i> </a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" asp-controller="Panel" asp-action="Index">Startsida  <i class="fas fa-home"></i> <span class="sr-only">(current)</span></a>

        </li>
        <li class="nav-item d-none">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Artiklar <i class="fas fa-user-edit"></i>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/Panel/create">Läggtill ny artikel</a>
                <a class="dropdown-item" href="/Panel/">Hantera artiklar</a>

            </div>
        </li>



        <li class="nav-item dropdown d-none">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Profil
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/Panel/create">Läggtill ny artikel</a>
                <a class="dropdown-item" href="/Panel/">Hantera artiklar</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>




    </ul>

     
    <form asp-action="Search" method="post" class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" name="keyword" placeholder="Sök" aria-label="Search" required>
        <button class="btn btn-success my-2 my-sm-0" type="submit">SÖK</button>
    </form>


 







</div>
</nav>

</header>
















<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>


     



<footer class="border-top footer bg-dark text-white">
    <div class="container text-center">
        Databasteknik och webbbaserade system 
 
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>